update start script for prod and node version

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -10,29 +10,35 @@ function cleanup {
 }
 trap cleanup SIGINT SIGTERM
 
-# if [[ -z "${KAFKA_CLIENT_CERT}" ]]; then
-#     echo "KAFKA_CLIENT_CERT is not set. Aborting"
-#     exit 1
-# fi
-
-# if [[ -z "${KAFKA_CLIENT_CERT_KEY}" ]]; then
-#     echo "KAFKA_CLIENT_CERT_KEY is not set. Aborting"
-#     exit 1
-# fi
-
-# if [[ -z "${KAFKA_URL}" ]]; then
-#     echo "KAFKA_URL is not set. Aborting"
-#     exit 1
-# fi
-
-# # Setup cert and cert key
-# rm -f client.crt client.key
-# echo -n "$KAFKA_CLIENT_CERT" > client.crt
-# echo -n "$KAFKA_CLIENT_CERT_KEY" > client.key
-
-# Build dist files in production
 if [ "${NODE_ENV}" = "production" ]; then
+  if [[ -z "${KAFKA_CLIENT_CERT}" ]]; then
+      echo "KAFKA_CLIENT_CERT is not set. Aborting"
+      exit 1
+  fi
+
+  if [[ -z "${KAFKA_CLIENT_CERT_KEY}" ]]; then
+      echo "KAFKA_CLIENT_CERT_KEY is not set. Aborting"
+      exit 1
+  fi
+
+  if [[ -z "${KAFKA_URL}" ]]; then
+      echo "KAFKA_URL is not set. Aborting"
+      exit 1
+  fi
+
+  # Setup cert and cert key
+  rm -f client.crt client.key
+  echo -n "$KAFKA_CLIENT_CERT" > client.crt
+  echo -n "$KAFKA_CLIENT_CERT_KEY" > client.key
+
+  # Build dist files in production
   webpack
+fi
+
+NODE_VERSION=`node --version`
+if [ "${NODE_VERSION:1:1}" -ne "6" ]; then
+  echo "Node v6 is required"
+  exit 1
 fi
 
 # Start it up
