Provide easier bootstrapping for local dev

diff --git a/viz/bin/start b/viz/bin/start
--- a/viz/bin/start
+++ b/viz/bin/start
@@ -11,13 +11,9 @@ function cleanup {
 trap cleanup SIGINT SIGTERM
 
 if [ "${NODE_ENV}" = "development" ]; then
-  export KAFKA_URL="$(heroku config:get KAFKA_URL)"
-  export KAFKA_CLIENT_CERT="$(heroku config:get KAFKA_CLIENT_CERT)"
-  export KAFKA_CLIENT_CERT_KEY="$(heroku config:get KAFKA_CLIENT_CERT_KEY)"
-  # TODO: use env var from heroku instance
-  # export KAFKA_TOPIC="$(heroku config:get KAFKA_TOPIC -a twitter-ingest)"
-  export KAFKA_TOPIC="ecommerce-logs"
-  export KAFKA_PREFIX=$(heroku config:get KAFKA_PREFIX)
+  # Redefine the env vars exported in this file if you don't have a Herok app from which to populate them.
+  # See README.md or app.json for a description of each var
+  source ./bin/env
 fi
 
 if [[ -z "${KAFKA_CLIENT_CERT}" ]]; then
@@ -32,6 +28,11 @@ fi
 
 if [[ -z "${KAFKA_URL}" ]]; then
   echo "KAFKA_URL is not set. Aborting"
+  exit 1
+fi
+
+if [[ -z "${KAFKA_TOPIC}" ]]; then
+  echo "KAFKA_TOPIC is not set. Aborting"
   exit 1
 fi
 
